  import Navbar from '@/app/components/Navbar'
  import {  Roboto,Rubik } from 'next/font/google'

  import './globals.css'
  
    export const roboto = Roboto({
      weight: ['400', '700'],
      style: ['normal', 'italic'],
      subsets: ['latin'],
      display: 'swap',

    })
    export const rubik = Rubik({
      weight: ['400', '700'],
      style: ['normal', 'italic'],
      subsets: ['latin'],
      display: 'swap',

    })


  
  export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <head>
          <link rel="stylesheet" href="/public/favicon.ico" />
          <title>@asdjosegarcia</title>
        </head>
        <body className={rubik.className}>
        <Navbar></Navbar>
          {children}
          </body>
      </html>
    )
  }

 

 
